[0m23:39:56.824364 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108016710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fca4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108057f10>]}


============================== 23:39:56.830262 | a9a8f88e-0be9-4bc0-a0c3-1fd25f2145c6 ==============================
[0m23:39:56.830262 [info ] [MainThread]: Running with dbt=1.7.10
[0m23:39:56.830712 [debug] [MainThread]: running dbt with arguments {'quiet': 'False', 'target_path': 'None', 'partial_parse': 'True', 'use_experimental_parser': 'False', 'printer_width': '80', 'static_parser': 'True', 'log_format': 'default', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'use_colors': 'True', 'profiles_dir': '/Users/gsokolov/.dbt', 'no_print': 'None', 'log_path': 'logs', 'debug': 'False', 'invocation_command': 'dbt build --project-dir=/Users/gsokolov/Library/CloudStorage/Dropbox/cube_octa --write-json --partial-parse --select funnels', 'indirect_selection': 'eager', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'warn_error': 'None', 'log_cache_events': 'False', 'cache_selected_only': 'False', 'version_check': 'True', 'fail_fast': 'False', 'introspect': 'True'}
[0m23:39:56.831227 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gsokolov/Library/CloudStorage/Dropbox/cube_octa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:39:56.832553 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.048984, "process_user_time": 0.921751, "process_kernel_time": 0.156354, "process_mem_max_rss": "117456896", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m23:39:56.833703 [debug] [MainThread]: Command `dbt build` failed at 23:39:56.833606 after 0.05 seconds
[0m23:39:56.833986 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fd5310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108068410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108068590>]}
[0m23:39:56.834223 [debug] [MainThread]: Flushing usage events
[0m05:38:57.325499 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d025d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c8ea10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d31250>]}


============================== 05:38:57.328319 | 3342af4d-106b-43d5-84e7-3f527906f51d ==============================
[0m05:38:57.328319 [info ] [MainThread]: Running with dbt=1.7.12
[0m05:38:57.328931 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'log_format': 'default', 'partial_parse': 'False', 'no_print': 'None', 'indirect_selection': 'eager', 'warn_error': 'None', 'log_path': 'logs', 'static_parser': 'True', 'printer_width': '80', 'cache_selected_only': 'False', 'invocation_command': 'dbt build --project-dir=/Users/gsokolov/Library/CloudStorage/Dropbox/cube_octa --write-json --no-partial-parse', 'send_anonymous_usage_stats': 'True', 'use_experimental_parser': 'False', 'use_colors': 'True', 'write_json': 'True', 'profiles_dir': '/Users/gsokolov/.dbt', 'introspect': 'True', 'log_cache_events': 'False', 'version_check': 'True', 'debug': 'False', 'quiet': 'False', 'fail_fast': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])'}
[0m05:38:57.329343 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gsokolov/Library/CloudStorage/Dropbox/cube_octa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:38:57.331398 [debug] [MainThread]: Resource report: {"command_name": "build", "command_wall_clock_time": 0.04908904, "process_user_time": 0.885263, "process_kernel_time": 0.176597, "process_mem_max_rss": "111296512", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m05:38:57.331767 [debug] [MainThread]: Command `dbt build` failed at 05:38:57.331687 after 0.05 seconds
[0m05:38:57.332006 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c9d890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d07d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10091c2d0>]}
[0m05:38:57.332241 [debug] [MainThread]: Flushing usage events
[0m19:16:44.468251 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108302910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b3a8d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b3fc8b0>]}


============================== 19:16:44.472779 | 34cb53fa-c875-4e4d-92cb-027ff09e3c90 ==============================
[0m19:16:44.472779 [info ] [MainThread]: Running with dbt=1.7.12
[0m19:16:44.473177 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/gsokolov/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt compile --project-dir=/Users/gsokolov/Library/CloudStorage/Dropbox/cube_octa --select push_problem', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:16:44.473558 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/gsokolov/Library/CloudStorage/Dropbox/cube_octa/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:16:44.475168 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 0.04303333, "process_user_time": 1.010108, "process_kernel_time": 0.123908, "process_mem_max_rss": "100073472", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:16:44.475590 [debug] [MainThread]: Command `dbt compile` failed at 19:16:44.475497 after 0.04 seconds
[0m19:16:44.475846 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108302910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b3fc9a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b3e9ca0>]}
[0m19:16:44.476092 [debug] [MainThread]: Flushing usage events
